package com.goldys.gymservice.model;

public class Program {

    /*
     * This class should have eight fields
     * (String programCode, String programName, String description, int
     * durationInMonths, float price, float discountRate, float currentPrice,
     * boolean isActive)
     * This class should also contain the getters and setters for the
     * fields along with the no-arg , parameterized	constructor and toString method.
     * The value of currentPrice should not be accepted from the user but should be
     * always calculated based on price and discountRate.
     *
     * programCode should be autogenerated.
     */

    private String programCode;
    private String programName;
    private String description;
    private int durationInMonths;
    private float price;
    private float discountRate;
    private float currentPrice;
    private boolean isActive;


    public String getProgramName() {
        return null;
    }

    public void setProgramName(String programName) {

    }

    public String getDescription() {
        return null;
    }

    public void setDescription(String description) {

    }

    public int getDurationInMonths() {
        return 0;
    }

    public void setDurationInMonths(int durationInMonths) {

    }

    public float getPrice() {
        return 0;
    }

    public void setPrice(float price) {

    }

    public float getDiscountRate() {
        return 0;
    }

    public void setDiscountRate(float discountRate) {

    }

    public float getCurrentPrice() {
        return 0;
    }

    public void setCurrentPrice() {

    }

    public String getProgramCode() {
        return null;
    }

    public void setProgramCode(String programCode) {

    }

    public boolean isActive() {
        return false;
    }

    public void setActive(boolean active) {

    }
}
