package com.goldys.enquiryservice.model;

public class Enquiry {
    /*
     * This class should have five fields
     * (String enquiryCode, String name, String email, String mobile, String query)
     * This class should also contain the getters and setters for the
     * fields along with the no-arg , parameterized	constructor and toString method.
     *
     * enquiryCode should be autogenerated.
     */



    public String getEnquiryCode() {
        return null;
    }

    public void setEnquiryCode(String enquiryCode) {

    }

    public String getName() {
        return null;
    }

    public void setName(String name) {

    }

    public String getEmail() {
        return null;
    }

    public void setEmail(String email) {

    }

    public String getMobile() {
        return null;
    }

    public void setMobile(String mobile) {

    }

    public String getQuery() {
        return null;
    }

    public void setQuery(String query) {

    }
}
