package com.goldys.ticketservice.model;

public class Ticket {

    /*
     * This class should have five fields
     * (String ticketId, String enquiryCode, boolean isOpen, String remarks, String executiveEmail)
     * This class should also contain the getters and setters for the
     * fields along with the no-arg , parameterized	constructor and toString method.
     *
     * ticketId should be autogenerated.
     */
    private String ticketId;

    private String EnquiryCode;

    private boolean isOpen;

    private String remarks;

    private String executiveEmail;

    public Ticket() {
    }

    public Ticket(String enquiryCode, boolean isOpen, String remarks, String executiveEmail) {

        EnquiryCode = enquiryCode;
        this.isOpen = isOpen;
        this.remarks = remarks;
        this.executiveEmail = executiveEmail;
    }

    public String getTicketId() {
        return ticketId;
    }

    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

    public String getEnquiryCode() {
        return EnquiryCode;
    }

    public void setEnquiryCode(String enquiryCode) {
        EnquiryCode = enquiryCode;
    }

    public boolean isOpen() {
        return isOpen;
    }

    public void setOpen(boolean open) {
        isOpen = open;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getExecutiveEmail() {
        return executiveEmail;
    }

    public void setExecutiveEmail(String executiveEmail) {
        this.executiveEmail = executiveEmail;
    }

}
