package com.goldys.ticketservice.model;

public class Ticket {

    /*
     * This class should have five fields
     * (String ticketId, String enquiryCode, boolean isOpen, String remarks,
     * String executiveEmail)
     * This class should also contain the getters and setters for the
     * fields along with the no-arg , parameterized	constructor and toString method.
     *
     * ticketId should be autogenerated.
     */

    private String ticketId;

    private String EnquiryCode;

    private boolean isOpen;

    private String remarks;

    private String executiveEmail;


    public String getTicketId() {
        return null;
    }

    public void setTicketId(String ticketId) {

    }

    public String getEnquiryCode() {
        return null;
    }

    public void setEnquiryCode(String enquiryCode) {

    }

    public boolean isOpen() {
        return false;
    }

    public void setOpen(boolean open) {

    }

    public String getRemarks() {
        return null;
    }

    public void setRemarks(String remarks) {

    }

    public String getExecutiveEmail() {
        return null;
    }

    public void setExecutiveEmail(String executiveEmail) {

    }

}
