package com.goldys.ticketservice.model;

import org.springframework.data.annotation.Id;

public class Ticket {

    /*
     * This class should have five fields
     * (String ticketId, String enquiryCode, boolean isOpen, String remarks,
     * String executiveEmail)
     * This class should also contain the getters and setters for the
     * fields along with the no-arg , parameterized	constructor and toString method.
     *
     * ticketId should be autogenerated.
     */
	@Id
	private String ticketId;
	private String enquiryCode;
	private boolean isOpen;
	private String remarks;
    private String executiveEmail;
    
	public String getTicketId() {
		return ticketId;
	}
	public void setTicketId(String ticketId) {
		this.ticketId = ticketId;
	}
	public String getEnquiryCode() {
		return enquiryCode;
	}
	public void setEnquiryCode(String enquiryCode) {
		this.enquiryCode = enquiryCode;
	}
	public boolean isOpen() {
		return isOpen;
	}
	public void setOpen(boolean isOpen) {
		this.isOpen = isOpen;
	}
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public String getExecutiveEmail() {
		return executiveEmail;
	}
	public void setExecutiveEmail(String executiveEmail) {
		this.executiveEmail = executiveEmail;
	}
	public Ticket(String enquiryCode, boolean isOpen, String remarks, String executiveEmail) {
		super();
		this.enquiryCode = enquiryCode;
		this.isOpen = isOpen;
		this.remarks = remarks;
		this.executiveEmail = executiveEmail;
	}

	public Ticket() {
    }
	
	@Override
	public String toString() {
		return "Ticket [ticketId=" + ticketId + ", enquiryCode=" + enquiryCode + ", isOpen=" + isOpen + ", remarks="
				+ remarks + ", executiveEmail=" + executiveEmail + "]";
	}
}
