# API gateway should start in port 9000.
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
# The API Gateway should have the following routes defined:
# - userservice (Eureka Service Registry serviceId: user-service)
# - gymservice (Eureka Service Registry serviceId: gym-service)
# - enquiryservice (Eureka Service Registry serviceId: enquiry-service)
# - ticketservice (Eureka Service Registry serviceId: ticket-service)
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"
server:
  port: 9000