# this file will contain the configuration for the Zuul API gateway.
#
# it should start with port number 9000 and the application name should be defined as 'api-gateway' which is the
# serviceId with which it will be registered with service registry.
#
# Zuul gateway should have the routes defined for the following:
# 1. UserService(serviceId: user-service)
# 2. GymService(serviceId: gym-service)
# 3. EnquiryService(serviceId: enquiry-service)
# 4. TicketService(serviceId: ticket-service)
#
# the Zuul gateway should be registered with Service Registry and should be able to interrogate the service registry
# for other services registered
#
