server:
  port: 9000
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
zuul:
  routes:
    userservice:
      serviceId: user-service
    gymservice:
      serviceId: gym-service
    enquiryservice:
      serviceId: enquiry-service
    ticketservice:
      serviceId: ticket-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka