# server should start with port number 8091. mongodb database name and
# port number should be accepted using environment variable

server:
  port: 8091
spring:
  application:
    name: gym-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100
  data:
    mongodb:
      database: programdb
      port: 27017
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka