# server should start with port number 8091. mongodb database name and
# port number should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"
server:
  port: 8091
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnesszone_productdb