# this file will contain the configuration for the GymService Microservice.
#
# it should start with port number 8091 and the application name should be defined as 'gym-service' which is the
# serviceId with which it will be registered with service registry.
#
# This microservice should be registered with Service Registry and should be able
#  to interrogate the service registry for other services registered
#

