# server should start with port number 8090. MySQL database config parameters
# should be accepted using environment variable

server:
  port: 8090
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

