# this file will contain the configuration for the UserService Microservice.
#
# it should start with port number 8090 and the application name should be defined as 'user-service' which is the
# serviceId with which it will be registered with service registry.
#
# This microservice should be registered with Service Registry and should be able
#  to interrogate the service registry for other services registered
#
