# server should start with port number 8090. MySQL database config parameters
# should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"
